name: flutter_animated_play_button
description: AnimatedPlayButton is a Flutter widget presenting several animating bars, which represent we are playing an item such as a track or a playlist..
version: 0.1.3
author: Weizhong Yang <zonble@gmail.com>
homepage: https://github.com/zonble/flutter_animated_play_button

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

