name: flutter_animated_play_button
description: AnimatedPlayButton is a Flutter widget presenting several animating bars, which represent we are playing an item such as a track or a playlist..
version: 0.2.1
homepage: https://github.com/zonble/flutter_animated_play_button

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'An animated button.'
    path: button.gif
 